Made corrections to reduce lines to 2

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,13 +1,2 @@
 #!/bin/bash
-
-if [ -z "$PYFILE" ]; then
-    echo "error: the PYFILE variable is not set"
-    exit 1
-fi
-
-if [ ! -f "$PYFILE" ]; then
-    echo "error: the PYFILE file does not exist"
-    exit 1
-fi
-
-python3 "$PYFILE"
+[ -z "$PYFILE" ] || [ ! -f "$PYFILE" ] && { echo "error: variable is not set or file does not exist"; exit 1; } && python3 "$PYFILE"
