Update 01 - made file 2 lines

diff --git a/0x00-python-hello_world/1-run_inline b/0x00-python-hello_world/1-run_inline
--- a/0x00-python-hello_world/1-run_inline
+++ b/0x00-python-hello_world/1-run_inline
@@ -1,8 +1,3 @@
 #!/bin/bash
 
-if [ -z "$PYCODE" ]; then
-    echo "error: the variable is not set"
-    exit 1
-fi
-
-python3 -c "$PYCODE"
+[ -z "$PYCODE" ] && echo "error: the variable is not set" && exit 1; python3 -c "$PYCODE"
